# Generated by Django 6.0.5 on 2026-06-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emh_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/img/avatar/teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='emh_web.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='courses', to='emh_web.topic'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='emh_web.course'),
        ),
    ]
