# Generated by Django 6.0.5 on 2026-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emh_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/avatar/teacher'),
        ),
    ]
