# Generated by Django 6.0.5 on 2026-06-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emh_web', '0002_account_teacher_avatar_teacher_course_taught_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='topics',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course_taught',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/avatar/teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='courses', to='emh_web.teacher'),
        ),
    ]
