# Generated by Django 6.0.5 on 2026-06-03 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emh_web', '0003_rename_topics_course_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Account',
            new_name='Login',
        ),
        migrations.AddField(
            model_name='student',
            name='citizen_card_number',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='student',
            name='nif',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
