# Generated by Django 6.0.5 on 2026-06-05 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emh_web', '0004_contact_rename_account_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='student',
            name='citizen_card_number',
            field=models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='O Cartão de Cidadão deve conter 8 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='nif',
            field=models.CharField(max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='O NIF deve conter 9 dígitos.')]),
        ),
    ]
