# Generated by Django 6.0.6 on 2026-06-17 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emh_web', '0005_delete_contact_delete_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(140)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='citizen_card_number',
            field=models.CharField(default='12345678 1 AA1', unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}\\s\\d{1}\\s[A-Z]{2}\\d{1}$', message="O Cartão de Cidadão deve estar no formato '12345678 1 AA1'.")]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='students', to='emh_web.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='floor',
            field=models.CharField(default='1E', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^.{2,}$', message='O Nome Completo deve ter pelo menos 2 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='municipality',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nif',
            field=models.CharField(default='123456789', unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='O NIF deve conter exatamente 9 dígitos.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='postcode',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{3}$', message="O código postal deve estar no formato '1234-567'.")]),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')]),
        ),
        migrations.AddField(
            model_name='student',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='emh_web.account'),
        ),
    ]
