# Generated by Django 6.0.6 on 2026-06-18 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emh_web', '0006_account_alter_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$', message='O Email deve estar em um formato válido.')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$', message='A Palavra-Passe deve ter pelo menos 8 caracteres, incluindo letras e números e caracteres especiais.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='postcode',
            field=models.CharField(validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{3}$', message="O código postal deve estar no formato '1234-567'.")]),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
    ]
