# Generated by Django 6.0.6 on 2026-06-25 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emh_web', '0007_alter_account_email_alter_account_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$', message='A Palavra-Passe deve estar num formato válido.')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='age_group',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='citizen_card_number',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}\\s\\d{1}\\s[A-Z]{2}\\d{1}$', message='O Cartão de Cidadão deve estar no formato válido.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='nif',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='O NIF deve estar no formato válido.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='postcode',
            field=models.CharField(validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{3}$', message='O Código Postal deve estar no formato válido.')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='training',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
