# Generated by Django 6.0.6 on 2026-06-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emh_web', '0008_alter_account_password_alter_course_age_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='avatar',
        ),
    ]
